
Vagrant.configure("2") do |config|
  BOX_IMAGE = "ubuntu/bionic64"

  config.vm.define "DB_VM" do |db|
    db.vm.box = BOX_IMAGE
    db.vm.hostname = "db-vm"
    db.vm.network "private_network", ip: "192.168.56.2"

    db.vm.provision "shell", path: "db_provision.sh", args: [
      ENV['DB_USER'], ENV['DB_PASS'], ENV['DB_NAME']
    ]
  end

  config.vm.define "APP_VM" do |app|
    app.vm.box = BOX_IMAGE
    app.vm.hostname = "app-vm"
    app.vm.network "private_network", ip: "192.168.56.3"
    app.vm.network "forwarded_port", guest: 8080, host: 8080

    app.vm.provision "shell", path: "app_provision.sh", args: [
      ENV['APP_USER'], ENV['PROJECT_DIR'], ENV['REPO_URL'],
      ENV['DB_HOST'], ENV['DB_PORT'], ENV['DB_NAME'],
      ENV['DB_USER'], ENV['DB_PASS']
    ]
  end
end
