version: "3.8"

services:
  app:
    build: .
    container_name: students_api
    command: gunicorn app:app -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
